front-end estático dos comentários no post
carolferraz/connect-ada-OiDevs pull request #40
Opened 2022-11-25 02:20 UTC by vi-lcandido

Falta colocar uma margem no placeholder e tb alterar a cor da escrita no text area

2022-11-25 11:42 UTC, amaendoas requested changes, later dismissed

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  font-family: "Roboto";
Ao inves de colocar 'roboto' direto, usa a variável que ta armazenada a font-family "--ff"

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  font-family: "Roboto";
Ao inves de colocar 'roboto' direto, usa a variável que ta armazenada a font-family "--ff"

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  font-family: "Roboto";
Ao inves de colocar 'roboto' direto, usa a variável que ta armazenada a font-family "--ff"

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  font-family: "Roboto";
Ao inves de colocar 'roboto' direto, usa a variável que ta armazenada a font-family "--ff"

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  background: #121214;
Ao inves de colocar a cor direto, usa a variável que ta armazenada o background "--bg"

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  font-family: "Roboto";
Ao inves de colocar 'roboto' direto, usa a variável que ta armazenada a font-family "--ff"

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  color: #7c7c8a;
usar alguma variável do root, se não tiver a cor pode criar

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  background-color: #29292e;
usar alguma variável do root, se não tiver a cor pode criar

2022-11-25 11:42 UTC, amaendoas commented on styles/styles.css
> +  color: #8d8d99;
usar alguma variável do root, se não tiver a cor pode criar

2022-11-26 19:02 UTC, Ivina-als approved these changes

2022-11-26 19:03 UTC, merged