Edit profile
carolferraz/connect-ada-OiDevs pull request #42
Opened 2022-11-25 06:39 UTC by Ivina-als

Coisas que fiz até agora:
1- coloque atribulo novo no data base =currentUserInSession
2- fiz método no database para guardar o currentUserInSession no localstorage
3- após usuário logar, o usuário é redirecionado para a página de feed
4 - já ta funcionando a edição de dados do currentUserInSession da página edit-profile

o que falta:
1- estilização da página de edição de perfil
2- setar no localstorage os novos dados do usuário logado na array de usuários do database
3- limpar inputs do edit-profile quando o usuário clica nos inputs

2022-11-25 12:09 UTC, amaendoas requested changes

2022-11-25 12:09 UTC, amaendoas commented on models/User.class.mjs
> +  constructor(name, password, email, role) {
no cadastro do usuário ele não passa o atributo 'role' apenas o nome, password e email, é bom ou tirar ou colocar coo default uma string vazia, mesma coisa pra imagem, o ideal é que tenha uma imagem default pra não exibir um erro pro usuário

2022-11-25 12:09 UTC, amaendoas commented on models/User.class.mjs
> +      "https://img.freepik.com/fotos-premium/retrato-de-cachorro-saindo-da-lingua_23-2148366828.jpg?w=2000";
esse link tem que sair do construtor

2022-11-25 12:09 UTC, amaendoas commented on pages/EditProfile/edit-profile.js
> +
modifiquei o header para não precisar ter essas informações, então pode apagar essas linhas

2022-11-25 14:45 UTC, Ivina-als commented on models/User.class.mjs
> +  constructor(name, password, email, role) {
Vou colocar string vazia para role. para imagem, ja tem imagem padrão

2022-11-25 14:51 UTC, Ivina-als commented on models/User.class.mjs
> +      "https://img.freepik.com/fotos-premium/retrato-de-cachorro-saindo-da-lingua_23-2148366828.jpg?w=2000";
Essa é a imagem padrão que todos os usuários novos recebem, na hora da criação da conta

2022-11-25 14:52 UTC, Ivina-als commented on pages/EditProfile/edit-profile.js
> +
blz

2022-11-25 14:58 UTC, amaendoas commented on models/User.class.mjs
> +      "https://img.freepik.com/fotos-premium/retrato-de-cachorro-saindo-da-lingua_23-2148366828.jpg?w=2000";
ok, achei que você tinha colocado pra testar e esquecido de trocar

2022-11-26 13:15 UTC, amaendoas approved these changes

2022-11-26 13:15 UTC, merged